import Head from 'next/head'
import Link from 'next/link'
import React, { useContext, useEffect, useState } from 'react'
import { Store } from '../utils/Store'

export default function Layout({ title, children }) {
    const { state } = useContext(Store)
    const { cart } = state

    const [cartItemsCount, setCartItemsCount] = useState(0)

    useEffect(()=>{
        setCartItemsCount(cart.cartItems.reduce((a,c)=>a+c.quantity,0))
    },[cart.cartItems])

    return (
        <div>
        <Head>
        <title> {title ? title + ' - NextMall' : 'NextMall'} </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="felx min-h-screen flex-col justify-between">
            <header>
                <nav className="flex h-12 items-center px-4 justify-between shadow-md bg-slate-200">
                    <Link href="/">
                        <a className="text-lg font-bold">Nextmall</a>
                    </Link>
                    <div>
                        <Link href="/cart">
                            <a className="p-2">Cart
                            {
                                cart.cartItems.length > 0 && (
                                    <span> {cart.cartItems.reduce()}</span>
                                )
                            }
                            </a>
                        </Link>
                        <Link href="/login">
                            <a className="p-2">Login</a>
                        </Link>
                    </div>
                </nav>
            </header>

            <main className="container"> {children} </main>

            <footer className="flex h-10 bg-red-100 justify-center items-center shadow-inner">
                <p> Copyright &copy; 2022 NextMall </p>
            </footer>
        </div>
    </div>
    )
}